import { ApiKeyConfig } from './apiKeys.types';

export const DEFAULT_API_KEYS: ApiKeyConfig[] = [
  {
    id: 'key-gemini-default',
    provider: 'gemini',
    name: 'Google Gemini Pro 2.5 (Built-In)',
    apiKey: 'BUILT_IN_ENV_GEMINI_KEY',
    modelName: 'gemini-2.5-flash',
    isActive: true,
    isDefault: true,
    createdAt: new Date().toISOString(),
    testStatus: 'valid',
  },
  {
    id: 'key-openai-preset',
    provider: 'openai',
    name: 'OpenAI GPT-4o Key',
    apiKey: '',
    modelName: 'gpt-4o',
    isActive: false,
    isDefault: false,
    createdAt: new Date().toISOString(),
    testStatus: 'untested',
  },
  {
    id: 'key-claude-preset',
    provider: 'anthropic',
    name: 'Anthropic Claude 3.5 Sonnet',
    apiKey: '',
    modelName: 'claude-3-5-sonnet-latest',
    isActive: false,
    isDefault: false,
    createdAt: new Date().toISOString(),
    testStatus: 'untested',
  },
  {
    id: 'key-deepseek-preset',
    provider: 'deepseek',
    name: 'DeepSeek V3 / R1 Engine',
    apiKey: '',
    modelName: 'deepseek-chat',
    baseUrl: 'https://api.deepseek.com',
    isActive: false,
    isDefault: false,
    createdAt: new Date().toISOString(),
    testStatus: 'untested',
  },
];
